name: Screenshot Comment
on:
  repository_dispatch:
    types: [screenshot-comment]

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - name: Find comment to update
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.client_payload.pr_number }}
          comment-author: 'github-actions[bot]'
          body-includes: You can download the generated screenshots from the workflow artifacts.

      - name: Create comment
        if: steps.find-comment.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.client_payload.pr_number }}
          body: |
            🖼️ **Screenshots created**

            You can download the generated screenshots from the workflow artifacts.

            _Please note that artifacts are only available for download for ${{ github.retention_days }} days._

            - Generated screenshots for ${{ github.event.client_payload.sha }} at ${{ github.event.client_payload.date }} ([download](${{ github.event.client_payload.download }})).

      - name: Update comment
        if: steps.find-comment.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          body: |
            - Generated screenshots for ${{ github.event.client_payload.sha }} at ${{ steps.on-success.date }} ([download](${{ github.event.client_payload.download }})).
